[package]
name = "lwext4-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "0.65"
fs_extra = "1.2.0"
make-cmd = "0.1.0"